### ISSUE TITLE
diozero description is incorrect

### ISSUE THREAD

**Issue by mattjlewis** [sgjava/java-periphery#1]
> limited to JDK 11. Almost 600 Java files compared to 33 for Java Periphery. Root access required in some situations.

diozero works with Java 8 onwards. The ~600 classes in not a fair comparison - the difference is related to completely different goals between the two libraries. As well as providing a lot of device classes, diozero includes its own portability layer with built-in default implementation and can work on Firmata devices like Arduino. java-periphery delegates to c-periphery and provides just low-level interfaces.

Also, diozero itself has no specific requirement to run as root - it purely depends on the O/S config itself and can usually be corrected by additional config, e.g. device tree permissions at boot.

**Comment by sgjava** [comment]
Totally fair comparison Java file count wise. Something with 600 files is inherently more complex and harder to test. As far as project focus my focus is clearly userspace IO (which is clearly stated). Again a fair comparison for someone looking for a simple IO solution. I make no claims otherwise.

So you regression tested everything with JDK17? I've done several large conversions from JDK 8 to 11 and all the transitive dependencies broke things. I see nowhere on your site where you support JDK 17. Saying you support Java 8 forward is disingenuous if you haven't tested "forward" specifically.

Also, can you show an implementation without root access for all IO services? Again I'll correct anything inaccurate.

**Comment by mattjlewis** [comment]
All I/O in diozero is userspace other than the memory mapped GPIO control which is the same as for java-periphery.

Yes, I do test with Java 8, 11 as well as 17 - no issues whatsoever.

The comparison on the number of classes would benefit from clarification - that diozero provides a full portability layer as well as high-level abstractions for I/O and includes support for a number of common categories of devices (ADCs, GPIO expanders, LEDs, OLEDs, motors, ...). Of course this does add complexity but that is what unit tests are for.

**Comment by sgjava** [comment]
The project comparison is very clear I'm only comparing IO (not a device library which can be easily ported from other projects). I need no portability layer as that's what the kernel provides. Also, I took a totally different approach with MMIO by using property files. No one off code needed for each supported board. I also provide the tooling to build these files without having to hand code from a datasheet. I didn't put that in the comparison. I removed the JDK limitation from the readme. If you provide configuration showing no root access required I'll remove that too.

Are you using mocks for your tests?

**Comment by mattjlewis** [comment]
I provide an I/O abstraction layer as I want full portability - java-periphery uses c-periphery as the I/O abstraction layer. Both of these use the exact same kernel interfaces. For this reason the two libraries have the exact same root access requirements.

Yes, I use some mocks - because diozero has its own I/O implementation it was fairly trivial to mock GPIO, I2C, SPI, serial device communication. I will always need additional unit tests.

**Comment by sgjava** [comment]
OK, so mocks are worthless in my opinion as they test nothing other than pre canned data unless you are using emulators on all the devices. Can you articulate what full portability is (you keep saying this, but userspace IO is already fully portable)? Yes, java-periphery uses c-periphery as you have stated several times. This is not a negative. It's a well built library. No use creating the wheel again. Do you write everything from scratch or so you leverage libraries and frameworks? I also generate all the JNI code as where you chose to hand code it. Does that make your code any better? I'm just leveraging these technologies to my benefit and it produces better quality code in my opinion.

**Comment by mattjlewis** [comment]
This isn't a discussion as to which is the best approach and I'm not stating anything negative about c-periphery or java-periphery, just correcting statements regarding diozero on your project page. c-periphery is clearly a fantastic library that has enabled a number of language bindings - that has not been my goal at all.

We have quite different goals, but fundamentally use the exact same kernel userspace APIs. Yes, the diozero approach has meant that I have had to implement some of what c-periphery implements but I wasn't aware of that library at the time.

Regarding "full portability", I'm referring to the diozero pluggable architecture that also allows communication with Arduino / Pico devices via Firmata as well as over the wire protocols such as gRPC.

**Comment by sgjava** [comment]
I think you are missing the big picture. I'm only comparing IO features and I made changes to the comparison already (thanks for reminding me about the MMIO stuff). The protocol layers are just unnecessary complexity as far as I'm concerned if you are looking for a Java IO layer (a lot of developers just want a cross platform wiringPi). As you stated we have different goals, but you can see where the projects intersect, right? I'm just contrasting the differences and made adjustments based on this discussion.

**Comment by sgjava** [comment]
OK, list the libraries that have the same level of SBC support (yours and mine maybe a couple more?) I'd say most do not have the same level of support is a true statement. diozero was in the same boat as the rest of the libraries until you adopted userspace method later in the game (I started this with my Userspace IO project in the beginning). Take a peek at your commits. Sure you can adopt any approach for MMIO, but I'm comparing to today, not the future. In any event I've addressed all your concerns that are material to my comparison which I'll let stand since it's the truth. Why not make your own comparison, so people can contrast your project against others. It's helpful if they are looking for specific features.

Like I said a lot of people could care less about Firmata. A lot of devs are using the SBC to do everything. It all depends on the application. If I wanted to support Firmata honestly I'd just get a good C library and generate the JNI wrappers. No need to code protocol from scratch.

**Comment by mattjlewis** [comment]
diozero has adopted userspace kernel interfaces from the very start. Let's end this discussion as I don't think you're going to update the text further and are missing my points.

**Comment by sgjava** [comment]
I'm not missing any points. Just go back and look at your "providers" in commit history (libgpiod only came out in kernel 4.8). Like I said I changed what you proved was incorrect, you should be happy with that instead of rambling on. As far as I'm concerned it's 100% accurate now. 600 classes vs 33 true, hand coded MMIO vs configuration driven true. Sorry you don't like those facts, but that's all they are.

**Comment by mattlewismule** [comment]
Prior to that I used sysfs like already stated.

**Comment by mattjlewis** [comment]
Prior to that I used sysfs as already stated. Anyway...

**Comment by sgjava** [comment]
sysfs was deprecated  3 years ago :) Anyways all good, the comparison is up to date now.
